### ISSUE TITLE
Argon with Bulma

### ISSUE THREAD

**Issue by slidenerd** [creativetimofficial/argon-design-system#100]
- First of all, fantastic work on the argon design system
- It is built on bootstrap which has jquery and popper as dependencies, they say you can use the css only version if you dont use modals , dropdowns etc which is almost impossible for most websites
- If you use it with Vue / Nuxt we have other problems like using Bootstrap-Vue as it does not Bootstrap's menus , dropdowns and modals clash with Vue's reactivity system
- In simple words, if you want to use it on Nuxt, it gets very bloated
- Would it be possible for you to make a separate argon project called argon-bulma or something that uses bulma as the base instead?

**Comment by rarestoma** [comment]
Hi @slidenerd,

Thank you for working with our products and for the kind words.

We have a plan for developing a Bulma based project, but we don't have a clear time when we will release it. If you can help us, we would be more than happy to launch this theme on Bulma as soon as possible.

Would you be interested in working together on a Bulma template for us?

Best regards,
Rares
