### ISSUE TITLE
update npm package to 1.2.0 

### ISSUE THREAD

**Issue by nasirkhan** [creativetimofficial/argon-design-system#107]
the npm package version is 1.1.0 where the github has 1.2.0. There are a number of bug fixes in this new version please update the npm package.

**Comment by rarestoma** [comment]
Hi @nasirkhan,

Thank you for working with our products.

We just updated it to 1.2.0: https://www.npmjs.com/package/argon-design-system-free.

Thank you,
Rares

**Comment by nasirkhan** [comment]
thank you for building awesome products.
