### ISSUE TITLE
No way to access product

### ISSUE THREAD

**Issue by Henshall** [creativetimofficial/argon-design-system#112]
I paid for a product, received a conformation email, double checked to make sure the funds were removed from my account, but do not have access to the content I paid for. There is not way to access it. 

The downloads section https://www.creative-tim.com/downloads says:

It seems that you don't have any product yet. 

Seems like the site is not recognizing that I have paid... My reference number is: 124417782

<img width="549" alt="Screen Shot 2020-06-13 at 10 39 05 AM" src="https://user-images.githubusercontent.com/20879253/84564487-63252380-ad62-11ea-87a0-62a9cf0fd0e2.png">

**Comment by dragosct10** [comment]
Hi, @Henshall! Thanks for using our products. I've sent you an email and there I've put you all the details about this order. 

Regards,
Dragos
