### ISSUE TITLE
How does the documentation works? 

### ISSUE THREAD

**Issue by Eencsio** [creativetimofficial/argon-design-system#15]
Hi! Your design system is awesome, and also the documentation, how can I create something like your documentation page? do you use any tool or framework? Specifically the vue docs
Thanks

**Comment by extrabright** [comment]
Hi,

For the Html version we used the Bootstrap structure made with Jekull, but customized some of the features. Regarding the Vue version, @cristijora might have some more details :)

But, for now, you can use our docs online only. If you want to achieve something like our docs, try reproducing it using the official Bootstrap docs. See their official repo.
