### ISSUE TITLE
navbar-transparent trigger

### ISSUE THREAD

**Issue by wefohubi** [creativetimofficial/argon-design-system#16]
Hi,

is there a way to customize navbar-transparent trigger? Right now it triggers on the middle of the container, and it looks chaotic :)
![navbar_transition](https://user-images.githubusercontent.com/42594540/44438237-e6421c00-a5c6-11e8-8c9b-49f0f22c668e.PNG)

**Comment by extrabright** [comment]
Hi,

Could you please give me more details about how did it happen? And what exactly are you trying to achieve?

**Comment by randallmlough** [comment]
There's a couple things that need to be changed to fix the weird scrolling of the navbar.

1. add  the `fixed-top` class to the navbar
2. Remove the positioning on the `.navbar-transparent` class – it's not need for this use case and it causes the conflict with .fixed-top
3. This one is more personal preference – change the headroom offset to 1 or close to it in argon.js file.

Doing the above will give you a much smoother scrolling navbar

**Comment by rarestoma** [comment]
Hi @wefohubi,

Thank you for working with our products and thank you for working with our products.

To customize the trigger you have to change the offset of the headroom in the argon.js file. This is placed right after the declaration of the headroom:

`var headroom  = new Headroom(document.querySelector("#navbar-main")`

I hope it helps.

All the best,
Rares
