### ISSUE TITLE
Headroom nav doesn’t spread across the whole screen 

### ISSUE THREAD

**Issue by Perksey** [creativetimofficial/argon-design-system#18]
# How to reproduce 
- Using an editor, change the class of the main navbar to “navbar navbar-main navbar-expand-lg navbar-dark bg-default headroom”
- Save it and open it in Firefox Quantum
- Scroll down, and when you scroll back up to trigger headroom, the navbar will no longer stretch to the full width of the screen

Haven’t done any further testing

**Comment by majkimajki** [comment]
Works only with class navbar-transparent - haven't tested why.

**Comment by matronator** [comment]
Can confirm in Safari as well. Only navbar-transparent seems to work correctly.

**Comment by Perksey** [comment]
@rarestoma This was closed a little prematurely. Can you confirm that this issue has been fixed?
