### ISSUE TITLE
More demos?

### ISSUE THREAD

**Issue by aw236** [creativetimofficial/argon-design-system#3]
Love this. The demos really helped with inspiration. Would like to see more demonstrations demonstrating more of the CSS styles/classes.

Also, would love to see a better registration flow that utilizes pagination.

**Comment by extrabright** [comment]
Thanks for the feedback! We are working on some great stuff that is going to come up in our Pro version. We will announce the release date soon :)

Regarding the registration flow, if you have an example please let me see :) 
Also, feel free to contribute if you have any great ideas for Argon. The community would much appreciate this.

Cheers!

**Comment by aw236** [comment]
Great, looking forward to it. An example registration flow might be: [Google AdWords registration](https://ads.google.com/um/Welcome/Home?hl=en&sourceid=awo&subid=us-en-di-g-aw-a-awhp_1!o2&sf=or&pli=1#oa). But it would be nice if you guys added an example of something like that in Argon that includes pagination for each step of the registration process. Basically, it would be great to have more examples for inspiration at: https://demos.creative-tim.com/argon-design-system/examples/

**Comment by extrabright** [comment]
We'll think about it. This is just the first version of Argon. Many cool stuff will be introduced in the near future. Thanks for your suggestions and support!
