### ISSUE TITLE
converting to navigation in wordpress

### ISSUE THREAD

**Issue by rayjencode** [creativetimofficial/argon-design-system#34]
Hi Tim, its my first time to convert the argon html to wordpress. can you please check the inserted php code for a navigation wordpress if the position is correct?

``  
    
    
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-default">
            <div class="container">
                <a class="navbar-brand" href="#"><img src="assets/img/brand/brand-white.png" alt="logo"></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-default" aria-controls="navbar-default" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbar-default">
                    <div class="navbar-collapse-header">
                        <div class="row">
                            <div class="col-6 collapse-brand">
                                <a href="index.html">
                                    <img src="assets/img/brand/brand.png" alt="logo">
                                </a>
                            </div>
                            <div class="col-6 collapse-close">
                                <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbar-default" aria-controls="navbar-default" aria-expanded="false" aria-label="Toggle navigation">
                                    <span></span>
                                    <span></span>
                                </button>
                            </div>
                        </div>
                    </div>

					
					<?php
						wp_nav_menu(array(
								'theme_location'	=> 'primary',
								'container'			=> 'nav',
								'menu_class'		=> 'navbar-nav ml-lg-auto'
							)
						);
					?>
					
        
                    <ul class="navbar-nav ml-lg-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="#">HOME</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">AIM</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">PARTNERS</span></a>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link" href="#" id="navbar-default_dropdown_1" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                FAQ
                            </a>
                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbar-default_dropdown_1">
                                <a class="dropdown-item" href="#">Action</a>
                                <a class="dropdown-item" href="#">Another action</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#">Something else here</a>
                            </div>
                        </li>
                    </ul>
        
                </div>
            </div>
        </nav>
    </header>

**Comment by rarestoma** [comment]
Hello,

Thank you for working with our products and sorry for the late response. Unfortunately, we do not work with wordpress so we can not tell you if it is correct or not.

Please check for a online tutorial.

All the best,
Rares
