### ISSUE TITLE
Utilities links broken in documentation on Typography page

### ISSUE THREAD

**Issue by JonathanReiss15** [creativetimofficial/argon-design-system#36]
The links to color utilities and typography on the [Typography page](https://demos.creative-tim.com/argon-design-system/docs/foundation/typography.html) utilities both return a 404 page

Links:
https://demos.creative-tim.com/argon-design-system/docs/foundation/argon-design-system/docs//utilities/text/
https://demos.creative-tim.com/argon-design-system/docs/foundation/argon-design-system/docs//utilities/colors/

**Comment by extrabright** [comment]
Where did you get those links? These are the correct ones:

https://demos.creative-tim.com/argon-design-system/docs/foundation/typography.html <https://demos.creative-tim.com/argon-design-system/docs/foundation/typography.html>
https://demos.creative-tim.com/argon-design-system/docs/foundation/colors.html <https://demos.creative-tim.com/argon-design-system/docs/foundation/colors.html>

**Comment by JonathanReiss15** [comment]
The links are in the Text Utilities section on the Typography page.  Link to section: https://demos.creative-tim.com/argon-design-system/docs/foundation/typography.html#text-utilities 

> Change text alignment, transform, style, weight, and color with our [text utilities](https://demos.creative-tim.com/argon-design-system/docs/foundation/argon-design-system/docs//utilities/text/) and [color utilities](https://demos.creative-tim.com/argon-design-system/docs/foundation/argon-design-system/docs//utilities/colors/).

**Comment by kidipridi** [comment]
links are still broken eh...

**Comment by GoodBoiDoggo** [comment]
still broken up to this date

**Comment by rarestoma** [comment]
Hello,

Thank you for the interest in our products.

We will fix those links in our next update.

All the best,
Rares
