### ISSUE TITLE
sidebar component

### ISSUE THREAD

**Issue by Phathdt** [creativetimofficial/argon-design-system#40]
do we have example sidebar component with subitem can toggle active ?

**Comment by rarestoma** [comment]
Hello,

Thank you for the interest in our products and sorry for our late response.

Please check out our argon dashboard, hope you will love it: https://demos.creative-tim.com/argon-dashboard/.

All the best,
Rares

**Comment by Mustafa-Rasheed** [comment]
how to change side bar menu in item component in argon Reactjs template

**Comment by rarestoma** [comment]
Hi @Mustafa-Rasheed,

Thank you for working with our products.

Please open the issue to the React version repo of Argon Design System product available here: https://github.com/creativetimofficial/argon-design-system-react/issues, so other people will easier find a solution if they have the same issue as you.

Best regards,
Rares
