### ISSUE TITLE
Profile page narrow-width screen bug

### ISSUE THREAD

**Issue by ownmas** [creativetimofficial/argon-design-system#42]
<img width="1050" alt="2018-10-30 21 03 37" src="https://user-images.githubusercontent.com/10982852/47739909-841d2b80-dc87-11e8-923a-c6bbd6cd8e05.png">

**Comment by rarestoma** [comment]
Hi,

Thank you for working with our products and sorry for the late response.

Please add these lines on the css file:

.profile-page .card-profile{
  z-index:2;
}

Hope it helps.

All the best,
Rares

**Comment by rarestoma** [comment]
Hello,

We also fixed that in our last update.

All the best,
Rares
