### ISSUE TITLE
Error in plugin 'sass': Running 'gulp build' throws error while working on “creative-tim” open source template.

### ISSUE THREAD

**Issue by KrunalDatascience** [creativetimofficial/argon-design-system#47]
I am new to sass/css/web design and i am trying to customize the argon [template](https://github.com/creativetimofficial/argon-design-system) for my project. After extracting the .zip file from above location I am running following sets of command in command prompt. Note - node.js is already installed in my system.

```
npm install -g gulp //installing gulp globally
npm init //initialization 
npm install --save-dev gulp //installing gulp locally - dev utility

npm install -g npm-install-all 
npm-install-all gulpfile.js //Installing all required modules from gulpfile.js 
```
After preparing my env. when i run the gulp task defined in the gulpfile.js using following code, it throws the mentioned error:

```
C:\Users\my_user\Documents\my_project>gulp build
[18:42:36] Using gulpfile ~\Documents\my_project\gulpfile.js
[18:42:36] Starting 'build'...
[18:42:36] Starting 'clean:dist'...
[18:42:36] Finished 'clean:dist' after 4.27 ms
[18:42:36] Starting 'scss'...
Error in plugin 'sass'
Message:
    assets\scss\custom\_mixins.scss
Error: File to import not found or unreadable: custom/mixins/alert.scss.
        on line 1 of assets/scss/custom/_mixins.scss
        from line 28 of assets/scss/argon.scss
>> @import "custom/mixins/alert.scss";

   ^

[18:42:37] Finished 'scss' after 805 ms
[18:42:37] Starting 'copy:css'...
[18:42:37] Finished 'copy:css' after 33 ms
[18:42:37] Starting 'copy:js'...
[18:42:37] Finished 'copy:js' after 11 ms
[18:42:37] Starting 'minify:js'...
[18:42:37] Finished 'minify:js' after 128 ms
[18:42:37] Starting 'minify:css'...
[18:42:38] Finished 'minify:css' after 992 ms
[18:42:38] Finished 'build' after 2 s
```
The content of all the file is unchanged and is the same as the git repo. So, incase if one wants to refer, one can check the link attached earlier.

I am using a windows-10 machine with:

```
>npm -v
6.4.1

>node -v
v8.12.0

>gulp -v
[19:04:01] CLI version 3.9.1
[19:04:01] Local version 3.9.1
```

**Comment by manghat** [comment]
Same issue here

**Comment by KrunalDatascience** [comment]
Why is it closed?

**Comment by rarestoma** [comment]
Hello,

Thank you for working with our products and sorry for closing it without answering, it was a mistake.

I tried it now and everything is working fine with the following versions: 
npm -v
6.9.0

node -v
v10.16.3

Please try updating it and let me know if it works. I hope it helps.

All the best,
Rares
