### ISSUE TITLE
Angular support

### ISSUE THREAD

**Issue by HamedMP** [creativetimofficial/argon-design-system#48]
Hi there,

Thank you for this beautiful design system, We love it. Can you please update us about the planned release time of Angular 6/7 version of the theme? 

Thank you!

**Comment by sharif-malik** [comment]
meanwhile checkout https://github.com/sharif-malik/argon-angular

**Comment by rarestoma** [comment]
Hi,

Here is the angular version of Argon Design System: https://www.creative-tim.com/product/argon-design-system-angular

All the best,
Rares
