### ISSUE TITLE
UI bug

### ISSUE THREAD

**Issue by oldsheepranchinn** [creativetimofficial/argon-design-system#51]
iPhone 8 Google Chrome version 70.0.3538.75
The Profile example page has a white triangle to set the angle of the top photograph over the top of the raised circle and the card.

**Comment by ordago** [comment]
![chrome_2018-12-30_18-59-40](https://user-images.githubusercontent.com/6376814/50550271-53487b00-0c65-11e9-93a3-28222b393ad3.png)

@oldsheepranchinn are you referring to this?

**Comment by oldsheepranchinn** [comment]
Yes! I just removed the angle on my site. Its was just 4 lines or so on the
page and the straight line looks good.

**Comment by raspgot** [comment]
You can remove the` z-index: 1` of the separator class also
