### ISSUE TITLE
Cannot use the noUISlider in the page. I have already included the js files for the same, still it's not working.

### ISSUE THREAD

**Issue by sanchit94** [creativetimofficial/argon-design-system#54]
![image](https://user-images.githubusercontent.com/33549324/51906283-d5090100-23e9-11e9-9d5b-d6c96faa8331.png)

**Comment by sanchit94** [comment]
Fixed it.

**Comment by smitpatelx** [comment]
> Fixed it.

How did you fix it?

**Comment by rarestoma** [comment]
Hi @sanchit94,

Thank you for working with our products and sorry for the late response.

To make the slider work you have also to add the nouislider.min.js library and be sure that the path to it is the right one. In our documentation(https://demos.creative-tim.com/argon-design-system/docs/plugins/sliders.html) we have examples and more information about how to properly use it.

I hope it helps.

All the best,
Rares

**Comment by sxshateri** [comment]
> Fixed it.

how? i tired but even on their own demo site, the slider doesn't show. tried with different browsers.
