### ISSUE TITLE
Headroom-not-top color static/mismatch

### ISSUE THREAD

**Issue by magumbasauce** [creativetimofficial/argon-design-system#56]
when using headroom, as you scroll with it out of the screen, and it switches the class to "headroom-not-top", that color in the CSS is a static value. So if I change the background shape gradient to say orange, then scroll down and IF the header snaps, the header is the original dark blue color. 

The header doesn't always snap into place, so i will probably just not use headroom anyway, but still an issue overall mainly because it takes a change to the CSS class to match the background color, which is not ideal.

**Comment by rarestoma** [comment]
Hello,

Thank you for working with our products and sorry for the late response.

Can you please show us a short video with the issue?

All the best,
Rares

**Comment by magumbasauce** [comment]
no worries! i haven't worked on that project for a while and when I do i am working more on the backend functionality rather than the front end. 

mmmm, not a video, but i grabbed a couple of screen shots for before and after Headroom triggers. 

The "shape" code is this:
    <div class="shape shape-style-1 bg-gradient-orange">
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
    </div>

So really just changed the color to bg-gradient-orange instead of the default color. 
![untriggered](https://user-images.githubusercontent.com/20244344/57820771-b0942300-7753-11e9-972e-bc08fb31c347.png)
![triggered](https://user-images.githubusercontent.com/20244344/57820772-b0942300-7753-11e9-90bf-7ab6bfc81c92.png)

**Comment by rarestoma** [comment]
Hi,

Oh, I understand... We will see what we can do to fix that issue in our next update.

All the best,
Rares
