### ISSUE TITLE
Stipe Elements in Dialog Box

### ISSUE THREAD

**Issue by R00118189** [creativetimofficial/argon-design-system#58]
For some reason stripe element error does not display with Argon theme, plain B4 displays no problem. Element is rendered but has display:none applied
Also there is slight glitch when typying in stripe element form backdrop goes 100% black when i leave the field it goes back to normal. I have this form in modal.

**Comment by rarestoma** [comment]
Hello,

Thank you for working with our products.

Can you please send us some photos so we can see exactly what happens?

All the best,
Rares
