### ISSUE TITLE
Missing file: docs.min.css

### ISSUE THREAD

**Issue by aw236** [creativetimofficial/argon-design-system#6]
In the example pages, the following .css is referenced: docs.min.css, like so:

`<link type="text/css" href="./assets/css/docs.min.css" rel="stylesheet">`

However, it is not included in the download.

**Comment by extrabright** [comment]
Hi,

The documentation is available online only. In the download package you will find only a page in the docs folder that will redirect you to our online documentation. 

Here is the link:
https://demos.creative-tim.com/argon-design-system/docs/getting-started/overview.html
