### ISSUE TITLE
Social icons are missing 

### ISSUE THREAD

**Issue by Sawalhah** [creativetimofficial/argon-design-system#60]
Facebook and Twitter icons are missing in homepage 
[https://demos.creative-tim.com/argon-design-system/examples/landing.html](https://demos.creative-tim.com/argon-design-system/examples/landing.html)
![image](https://user-images.githubusercontent.com/10211157/53663901-ac398d00-3c6f-11e9-8839-7790b2e3e7e8.png)

**Comment by rarestoma** [comment]
Hello,

Thank you for the interest in our products.

Please check your internet connection, it works now.

All the best,
Rares
