### ISSUE TITLE
path error

### ISSUE THREAD

**Issue by lpj145** [creativetimofficial/argon-design-system#68]
https://github.com/creativetimofficial/argon-design-system/blob/62db8b2add15308ca83adaf864cc6b6a929d30b7/assets/scss/argon.scss#L65

Why is referenced a error ? no have anyone file referencend at this file.

![image](https://user-images.githubusercontent.com/11980109/58442975-63a23c00-80c5-11e9-95be-9449c4998fae.png)

![image](https://user-images.githubusercontent.com/11980109/58442980-68ff8680-80c5-11e9-88c8-b505f748a615.png)

**Comment by rarestoma** [comment]
Hi,

Thank you for working with our products.

Can you please give me more details? What steps did you follow after downloading the project?

All the best,
Rares

**Comment by hfloyd** [comment]
I am having the same issue.

I have copied the files into my website project, I opened "\scss\custom\_variables.scss" and updated some color Hex codes, then Saved the file. I am using "CompileSass" in Visual Studio, so on Save, it compiles. The output messages I am seeing:

```
CompileSass 11:11:19 AM: Detected save to _variables.
CompileSass 11:11:20 AM: Sass compilation failed for C:/.../Assets/scss/custom/_mixins.scss:1, column 1:
CompileSass 11:11:20 AM: File to import not found or unreadable: custom/mixins/alert.scss
Parent style sheet: C:/../Assets/scss/custom/_mixins.scss
CompileSass 11:11:20 AM: Error: File to import not found or unreadable: custom/mixins/alert.scss
       Parent style sheet: C:/../Assets/scss/custom/_mixins.scss
        on line 1 of ../../../../../../../Assets/scss/custom/_mixins.scss
>> @import "custom/mixins/alert.scss";
   ^
```

**Comment by hfloyd** [comment]
I was able to resolve the issue by updating "/custom/_utilities.scss" & "/custom/_mixins.scss" to remove "custom/" from all the import paths.

example:

```
@import "custom/mixins/alert.scss";
@import "custom/mixins/badge.scss";
@import "custom/mixins/background-variant.scss";
@import "custom/mixins/buttons.scss";
@import "custom/mixins/forms.scss";
@import "custom/mixins/icon.scss"; 
@import "custom/mixins/modals.scss";
@import "custom/mixins/popover.scss"; 
```

became

```
@import "mixins/alert.scss";
@import "mixins/badge.scss";
@import "mixins/background-variant.scss";
@import "mixins/buttons.scss";
@import "mixins/forms.scss";
@import "mixins/icon.scss"; 
@import "mixins/modals.scss";
@import "mixins/popover.scss"; 
```

**Comment by rarestoma** [comment]
Hi,

This issue was resolved in our last version.

Thank you,
Rares
