### ISSUE TITLE
scss files are outdated

### ISSUE THREAD

**Issue by Sawalhah** [creativetimofficial/argon-design-system#70]
Hi,
I tried to compile scss files to new css file
but I got a different style
before compiling file from sass 
![image](https://user-images.githubusercontent.com/10211157/59147222-83106180-8a01-11e9-913a-32aed4112e63.png)

and after compiling
![image](https://user-images.githubusercontent.com/10211157/59147251-fade8c00-8a01-11e9-8cff-b1efaf5c492d.png)

**Comment by rarestoma** [comment]
Hi,

Thank you for your interest in our products.

Did you modify something? How did you compile the scss files?

All the best,
Rares

**Comment by Sawalhah** [comment]
Hi,
I've edited some paths in scss files #68 
and uses node scss to compile the scss

**note:
after further investigation 
I've added some classes to support RTL and I think I missed something

thanks @rarestoma 

Regards,
Mohammad
