### ISSUE TITLE
Change -warning color 

### ISSUE THREAD

**Issue by JuneMoon** [creativetimofficial/argon-design-system#73]
I've changed the -warning color to various classes, btn-warning, text-warning, etc.
I changed the hex and rgba values, but when I run the project I still get the default warning color from the theme. HELP!

**Comment by rarestoma** [comment]
Hello,

Thank you for working with our products. 

Can you please give me more details? Did you change the colors for all the classes? Can you show some code with the changes you made and the results after it?

All the best,
Rares
