### ISSUE TITLE
Accessibility issues with components

### ISSUE THREAD

**Issue by jamesrweb** [creativetimofficial/argon-design-system#75]
Hi there, I came across this design system and thought at first that it was great as a component library, however, as I always do before using a design system like this, I did accessibility tests on a couple of components and I have to say that there are some major behavioural issues on certain components, for example:

- Focus styles on buttons seem to be missing, here is a good article on the topic: https://css-tricks.com/focusing-on-focus-styles/
- Modals don't meet authoring practices: https://www.w3.org/TR/wai-aria-practices-1.1/#dialog_modal
- Tabs don't meet authoring practices: https://www.w3.org/TR/wai-aria-practices-1.1/#tabpanel

These are major accessibility issues that require seeing to and only 3 of the 50+ available that I have looked into.

Comment would be much appreciated and happy to help if/where required.

**Comment by rarestoma** [comment]
Hi,

Thank you for the interest in our products

We will take a closer look at all your details these articles provide and we will see how we can fix that.

All the best,
Rares

**Comment by jamesrweb** [comment]
@rarestoma I am happy to audit all of the components for accessibility issues but I figured beginning with these is a start, would you like me to go ahead and run some component audits for you and the team to implement fixed to?

**Comment by rarestoma** [comment]
Hi @jamesrweb,

I talked with the team and for the moment we will continue with our development and in the future, we will take a closer look at accessibility tests.

Thank you,
Rares

**Comment by jamesrweb** [comment]
In this case, I would advise a rething. 95% of public websites are inaccessible, 1/8 people in the world suffer from pernament, situational or temporary disabilities at any one time, it happens to us all. In the EU alone, 80 million people at any one time have access needs and the implementation by us as developers hinders them. About 1 in 5 Americans have some kind of disability, and 1 in 10 have a severe disability. Those with access needs are 70% more likely to live in poverty and yet, if you look at america for example, those with disabilities have almost the same spending power as the black and hispanic communities put together. So even if you don't see the empathetic case, the business case is there for the project to showcase: "Hey, we actually give a shit". Happy to throw more facts, figures or even provide implementation advice, it's not that hard when you know how ;). Just some thoughts.

**Comment by rarestoma** [comment]
Hi @jamesrweb,

I am sorry for the misunderstanding. :pensive:

We really appreciate your implication and we want to make these changes as soon as possible. Unfortunately, we can’t start working on these issues right now because we have other priorities that we need to solve. The statements you showed us are really really sad and it would be good if we could provide a faster integration of these problems maybe with the help of the Open source community as the project is released under MIT License.

I hope everything is all right and you understand that our main purpose is to make a better world with better websites.

Thank you,
Rares

**Comment by jamesrweb** [comment]
@rarestoma all good, just don't kick it down the road "accessibility is like a blueberry muffin, you can't put the berries in afterwards" as the saying goes. The more you develop, the more refactor time is required. All new components should have a11y built in and all old ones rebuilt to include it. I'd be happy to share resources and if you have any questions, I am more than happy to contribute answers and help where possible, just ask or point in the right direction. Thanks for the answer and let's keep pushing for a better web as you said.
