### ISSUE TITLE
Modal Grayed Out on Example landing page

### ISSUE THREAD

**Issue by hCoureau** [creativetimofficial/argon-design-system#76]
Hi,

I will include screenshots but i copied the code from the docs and it just does this? Not Sure why, really need it for a project so please could you provide a fix? 
![image](https://user-images.githubusercontent.com/31824325/61887740-18a47980-aefa-11e9-89e3-e12ff5b35dd9.png)
![image](https://user-images.githubusercontent.com/31824325/61887752-1f32f100-aefa-11e9-8130-ab35381c1f81.png)

Thanks

**Comment by rarestoma** [comment]
Hi,

Thank you for your interest in our products.

We have a few examples of the modals here https://demos.creative-tim.com/argon-design-system/index.html. Did you follow this structure?

Can you please give me a codepen link so I can see clearly all the structure of the code?

All the best,
Rares

**Comment by hCoureau** [comment]
Hi Rares, 
Couldn't even get the modal to launch at all on code pen so i have put a link below to a fork and my edits on github where you can see the code fully. 
https://hcoureau.github.io/argon-design-system/
Thanks,
Harry

**Comment by rarestoma** [comment]
Hi,

Please modify the code in this way:
1. get the modal out of the .card's div but keep it in the .col-lg-4 like:
```
<div class="col-lg-4">
<div class="card">
<div class="card-body">
// Keep here the modal button 
</div>
</div>
// Move here the modal
</div>
```

2. Remove the 'mt--200' class from the modal's section.

Now it should work fine.

I hope it helps. Please let me know if you need help with anything else.

All the best, 
Rares
