### ISSUE TITLE
how use pagination

### ISSUE THREAD

**Issue by ewgenij87snwork** [creativetimofficial/argon-design-system#79]
Hello, friends! I I output data so:
```
<template>
	<div>
		<task
		v-for="item in items"
		v-bind:key="item.name"
		v-bind:name="item.name"
		v-bind:description="item.description"
		v-bind:func="item.func"
		/>
	</div>
</template>
<script>
import arraytask from "@/data/arraytask.json";
export default {
	name: 'arrayz',
	components: {
		'task': () => import('@/components/task')
	},
	data: function() {
		return {
			items: arraytask
		}
	},	
}
</script>
```

I can't uderstand how connect pagination with displays my data. (Sorry, for my English)

**Comment by rarestoma** [comment]
Hi @ewgenij87snwork and thank you for working with our products! Please open an issue on the official repo of the Argon Design System Vue (https://github.com/creativetimofficial/vue-argon-design-system/issues) so our Vue.js team will give you the best answer. All the best, Rares!
