### ISSUE TITLE
Compatibility with SASS-Loader 8.0.0

### ISSUE THREAD

**Issue by mikeychowy** [creativetimofficial/argon-design-system#80]
It seems that the sass options "fiber" is not compatible with the new version of sass-loader, what can i do to make it compatible?

**Comment by rarestoma** [comment]
Hi @mikeychowy,

Thank you for working with our products. Unfortunately, we are not working with sass-loader :( Please check their official documentation and I hope you'll fix this issue. 

All the best,
Rares
