### ISSUE TITLE
How to upadte font awesome to v5

### ISSUE THREAD

**Issue by eppro** [creativetimofficial/argon-design-system#81]
How to update font awesome, I tried replacing the files in css/theme/vendor/font-awesome but does't work

**Comment by rarestoma** [comment]
Hi @eppro,

Thank you for working with our products. You have to replace the font-awesome.css file to all.css file from your downloaded folder. After that, you have also to put the webfonts folder in the argon-design-system/assets/vendor/font-awesome. Now it should work.

Please let me know if everything works properly now.

All the best,
Rares
