### ISSUE TITLE
Smooth scroll

### ISSUE THREAD

**Issue by sveeetch** [creativetimofficial/argon-design-system#83]
How to make in this theme smooth scroll (by click on #button)

**Comment by rarestoma** [comment]
Hi @sveeetch,

Thank you for working with our products.

Please add this code in the js file:

```
    $("[href^='#']").on('click', function(e) {

         // prevent default anchor click behavior
         e.preventDefault();

         // store hash
         var hash = this.hash;

         // animate
         $('html, body').animate({
             scrollTop: $(hash).offset().top
           }, 700, function(){

             // add hash to url
             window.location.hash = hash;
           });

      });
```

I hope it helps.

All the best,
Rares

**Comment by sveeetch** [comment]
> Hi @sveeetch,
> 
> Thank you for working with our products.
> 
> Please add this code in the js file:
> 
> ```
>     $("[href^='#']").on('click', function(e) {
> 
>          // prevent default anchor click behavior
>          e.preventDefault();
> 
>          // store hash
>          var hash = this.hash;
> 
>          // animate
>          $('html, body').animate({
>              scrollTop: $(hash).offset().top
>            }, 700, function(){
> 
>              // add hash to url
>              window.location.hash = hash;
>            });
> 
>       });
> ```
> 
> I hope it helps.
> 
> All the best,
> Rares

Thank!
