### ISSUE TITLE
Tailwind Version?

### ISSUE THREAD

**Issue by intellow** [creativetimofficial/argon-design-system#85]
Do you have any plans to release a tailwind css version of Argon?

**Comment by rarestoma** [comment]
Hi,

Thank you for your interest in our products.

We have a plan for the Tailwind Version, but we don't know exactly when we will start working on it.

I hope it helps.

All the best,
Rares

**Comment by imrealashu** [comment]
Hi @rarestoma any development progress on the Tailwind version of the theme yet?
