### ISSUE TITLE
v1.0.1 ship list

### ISSUE THREAD

**Issue by extrabright** [creativetimofficial/argon-design-system#9]
Work in progress ...

**Highlights**

This version comes with some bug fixes and also a new page header for the index page. Feel free to download it again and simply replace the css/js from your project with the newer ones.

**CSS**

- #7 Removed the double body/html tags in SCSS/CSS
- #8 Solved the syntax error in the calc() function

**Comment by alexandru-paduraru** [comment]
@extrabright @marqbeniamin @dragosct10 this looks nice, should we do it on Projects: https://github.com/creativetimofficial/argon-design-system/projects ? So other persons can see what we are working on and when we prepare a release? Just an idea 😸

**Comment by extrabright** [comment]
@alexandru-paduraru Pretty cool, huh? :tada: :tada: :tada: 
https://github.com/creativetimofficial/argon-design-system/projects/1

**Comment by dragosct10** [comment]
This looks pretty nice!
