### ISSUE TITLE
Actions menu isn't properly displayed

### ISSUE THREAD

**Issue by AlexZaytsav** [creativetimofficial/argon-design-system#95]
![Screenshot 2020-02-21 at 15 30 33](https://user-images.githubusercontent.com/1477925/75079914-4917ba80-54bf-11ea-9e53-d82df1cffd19.png)

Actions menu is overlapped by tables footer If there is only one row in the table.

**Comment by rarestoma** [comment]
Hi @AlexZaytsav,

Thank you for working with our products.

It seems like this table is from the argon dashboard product. Can you please open this issue there so it will be visible also for all the dashboard users? 

Thank you,
Rares

**Comment by AlexZaytsav** [comment]
Hi @rarestoma,

Thank you for the response.

I opened this issue there: https://github.com/creativetimofficial/argon-dashboard/issues/40.

Thank you,
Alex.
