### ISSUE TITLE
Toggle button dosen't work on Chrome Version 80

### ISSUE THREAD

**Issue by neelansh15** [creativetimofficial/argon-design-system#98]
Although the docs mention that it should work in the last two versions, it doesn't work on my Google Chrome running on Windows 10.  I have the latest version as of March 2020.

__Chrome Version:__
```
Google Chrome | 80.0.3987.149 (Official Build) (64-bit) (cohort: Stable)
Revision | 5f4eb224680e5d7dca88504586e9fd951840cac6-refs/branch-heads/3987_137@{#16}
```
It works on Microsoft Edge just fine, but I am looking for help with Chrome.

**Comment by rarestoma** [comment]
Hi @neelansh15 ,

Thank you for working with our products.

Can you please help me with more details? Did you have any errors in console using our toggle button?

Thank you,
Rares
